import { useEffect, useState } from 'react'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog'
type API = <T>(path:string, options?:RequestInit)=>Promise<T>
type Order = {store_id:number;odoo_order_id:number;odoo_order_name:string}
type Details = {store_id:number;website_id:number;odoo_order_id?:number;odoo_order_name:string;recipient:string;customer_name:string;order_total:string;currency:string;sender_domain:string}
type Message = Details & {id:number;body:string;status:string;actor:string;actor_identity:string;created_at:string;last_error?:string;segment_estimate:{parts:number;encoding:string}}
const base='/api/after-order/sms/manual'
export function ManualSmsDetails({api,id,onChange}:{api:API;id:number;onChange:()=>void}) {
  const [row,setRow]=useState<Message|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false)
  useEffect(()=>{api<Message>(`${base}/${id}`).then(setRow).catch(e=>setError(String(e)))},[api,id])
  async function refresh(){setBusy(true);try{setRow(await api<Message>(`${base}/${id}/refresh`,{method:'POST'}));onChange()}catch(e){setError(String(e))}finally{setBusy(false)}}
  return <div className="grid gap-3">{error&&<p role="alert">{error}</p>}{row&&<><p>{row.recipient} · {row.status} · Twilio</p><p>{row.customer_name} {row.order_total} {row.currency}</p><div className="sms-message-body whitespace-pre-wrap">{row.body}</div><p>Team member: {row.actor}</p><small>{row.actor_identity} · {new Date(row.created_at).toLocaleString()}</small>{row.last_error&&<p role="alert">{row.last_error}</p>}<Button disabled={busy} variant="outline" onClick={()=>void refresh()}>Refresh delivery status</Button><p className="text-sm">Provider acceptance does not confirm delivery. No automatic resend is performed for manual messages.</p></>}</div>
}
export function ManualSmsComposer({api,storeId,onSent}:{api:API;storeId:string;onSent:()=>void}) {
  const [open,setOpen]=useState(false);const [mode,setMode]=useState('order');const [q,setQ]=useState('');const [orders,setOrders]=useState<Order[]>([])
  const [sites,setSites]=useState<{store_id:number;website_id:number;label:string}[]>([]);const [site,setSite]=useState('')
  const [details,setDetails]=useState<Details|null>(null);const [phone,setPhone]=useState('');const [body,setBody]=useState('');const [actor,setActor]=useState('');const [consent,setConsent]=useState(false)
  const [preview,setPreview]=useState<Message|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [key,setKey]=useState(()=>crypto.randomUUID())
  useEffect(()=>{if(open)api<typeof sites>(base+'/sites').then(setSites).catch(e=>setError(String(e)))},[open,api])
  useEffect(()=>{if(!open||mode!=='order'||q.trim().length<2){setOrders([]);return}const c=new AbortController();const timer=setTimeout(()=>{api<Order[]>(`${base}/orders?${new URLSearchParams({q,store_id:storeId||'0'})}`,{signal:c.signal}).then(setOrders).catch(e=>{if(!c.signal.aborted)setError(String(e))})},300);return()=>{clearTimeout(timer);c.abort()}},[open,mode,q,storeId,api])
  async function choose(value:string){setDetails(null);setBusy(true);setError('');try{const [store,order]=value.split(':');setDetails(await api<Details>(`${base}/order?store_id=${store}&order_id=${order}`))}catch(e){setError(String(e))}finally{setBusy(false)}}
  async function prepare(){setBusy(true);setError('');try{const [store,website]=site.split(':');const target=mode==='order'?{store_id:details?.store_id,website_id:details?.website_id,order_id:details?.odoo_order_id}:{store_id:Number(store),website_id:Number(website),recipient:phone};setPreview(await api<Message>(base+'/preview',{method:'POST',body:JSON.stringify({...target,body,actor,consent_confirmed:consent,request_key:key})}));onSent()}catch(e){setError(String(e))}finally{setBusy(false)}}
  async function send(){if(!preview)return;setBusy(true);setError('');try{const result=await api<Message>(`${base}/${preview.id}/send`,{method:'POST',body:JSON.stringify({confirm:true})});setPreview({...preview,...result});onSent()}catch(e){setError(String(e)+' Check the SMS log before trying again.')}finally{setBusy(false)}}
  function reset(){setPreview(null);setBody('');setDetails(null);setPhone('');setQ('');setConsent(false);setError('');setKey(crypto.randomUUID())}
  return <><Button onClick={()=>{reset();setOpen(true)}}>Send manual SMS</Button><Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v)}}><DialogContent className="sms-message-dialog"><DialogHeader><DialogTitle>Send manual SMS</DialogTitle><DialogDescription>Compose a customer service message. Nothing sends until you preview and click Send SMS.</DialogDescription></DialogHeader><div className="grid gap-4">
  {error&&<p role="alert" className="sms-error">{error}</p>}
  {!preview?<><label>Recipient source<select className="form-select" disabled={busy} value={mode} onChange={e=>{setMode(e.target.value);setDetails(null);setKey(crypto.randomUUID())}}><option value="order">Select an order</option><option value="phone">Enter a mobile number</option></select></label>
  {mode==='order'?<><label>Search order number<input className="form-control" value={q} onChange={e=>{setQ(e.target.value);setDetails(null)}} placeholder="NC…" disabled={busy}/></label><label>Matching orders<select className="form-select" disabled={busy} value={details?`${details.store_id}:${details.odoo_order_id}`:''} onChange={e=>{if(e.target.value)void choose(e.target.value)}}><option value="">Select an order</option>{orders.map(x=><option key={`${x.store_id}:${x.odoo_order_id}`} value={`${x.store_id}:${x.odoo_order_id}`}>{x.odoo_order_name} · Store {x.store_id}</option>)}</select></label>{details&&<div className="rounded border p-3"><strong>{details.customer_name}</strong><p>{details.recipient}</p><p>{details.sender_domain}</p><p>Order total: {details.order_total} {details.currency}</p></div>}</>:<><label>Sending website<select className="form-select" value={site} disabled={busy} onChange={e=>setSite(e.target.value)}><option value="">Select a website</option>{sites.map(x=><option key={`${x.store_id}:${x.website_id}`} value={`${x.store_id}:${x.website_id}`}>{x.label}</option>)}</select></label><label>Mobile number<input className="form-control" type="tel" placeholder="+country code and number" value={phone} disabled={busy} onChange={e=>setPhone(e.target.value)}/></label></>}
  <label>Team member name<input className="form-control" value={actor} maxLength={100} disabled={busy} onChange={e=>setActor(e.target.value)}/><small>Recorded as entered; this app uses shared admin access.</small></label>
  <label>Message<textarea className="form-control w-full min-h-40" maxLength={1000} disabled={busy} value={body} onChange={e=>setBody(e.target.value)}/></label><small>{body.length}/1,000 characters. Estimated SMS parts and encoding appear in the preview. Text sends exactly as entered, without automatic translation.</small>
  <label><input type="checkbox" checked={consent} disabled={busy} onChange={e=>setConsent(e.target.checked)}/> This is an authorized customer-service message, not unsolicited marketing.</label>
  <Button disabled={busy||!body.trim()||!actor.trim()||!consent||(mode==='order'?!details:!site||!phone)} onClick={()=>void prepare()}>Preview SMS</Button></>:<><p><strong>{preview.odoo_order_name}</strong> · {preview.sender_domain}</p><p>{preview.customer_name} · {preview.recipient}</p><p>{preview.order_total} {preview.currency}</p><div className="sms-message-body whitespace-pre-wrap">{preview.body}</div><small>{preview.segment_estimate.parts} estimated billable part(s) · {preview.segment_estimate.encoding}. Twilio rates apply.</small><p>Status: {preview.status}</p>{preview.last_error&&<p role="alert">{preview.last_error}</p>}{preview.status==='draft'?<div className="sms-actions"><Button variant="outline" disabled={busy} onClick={()=>{setPreview(null);setKey(crypto.randomUUID())}}>Edit</Button><Button disabled={busy} onClick={()=>void send()}>{busy?'Sending…':'Send SMS'}</Button></div>:<p>Recorded in SMS log. Accepted/queued is not confirmed delivery.</p>}</>}
  </div></DialogContent></Dialog></>
}
